# Site settings
title: jonbee.be
name: jonbee.be
email: me@jonbeebe.net
description: > # this means to ignore newlines until "baseurl:"
  Web and technology links and articles by Jonathan Beebe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonbee.be" # the base hostname & protocol for your site

markdown: kramdown
highlighter: pygments

permalink: :year/:month/:title/
paginate: 30

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE', 'Makefile']