# Site settings
title: jonbee.be
name: jonbee.be
author: Jonathan Beebe
email: me@jonbeebe.net
description: > # this means to ignore newlines until "baseurl:"
    Tech industry links and articles by Jonathan Beebe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonbee.be" # the base hostname & protocol for your site

markdown: kramdown
highlighter: rouge

permalink: :year/:month/:title/
paginate: 30
lsi: false
gems: ['jekyll-paginate']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE', 'Makefile']
