# Site settings
title: jonbeebe.net
name: Jonathan Beebe
author: Jonathan Beebe
email: me@jonbeebe.net
description: > # this means to ignore newlines until "baseurl:"
    Tech industry links and articles by Jonathan Beebe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonbeebe.net" # the base hostname & protocol for your site
feed_url: "http://feeds.feedburner.com/jonbeebe-net"
excerpt_separator: <!--more-->

markdown: kramdown
highlighter: rouge

permalink: :year/:month/:title/
paginate: 30
lsi: false
gems: ['jekyll-paginate']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE', 'Makefile']
